name: HesHereAllWeek
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32277
title: "He's Here All Week"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c6c6'
    - '#3c3c3c'
    - '#0b0b09'
    - '#939393'
    - '#6c6c6c'
  brandStrength: 0.6571552660316229
  lightness: 0.2899652512278408
  saturation: 0.6729004855733365
  rhythmicContrast: 0.9339284156449139
purpose: []
